#!/bin/bash
#
# Check if tracker service has been started and add libtracker to ld_preload list
#
function tracker_ld_preload()
{   
    systemctl -q is-active tracker && echo libtracker.so
}

#
# expose our preload function to the wrapper script...
#
ld_preload_funcs="${ld_preload_funcs} tracker_ld_preload"
