#! /bin/bash
#
# Build and deploy - tracker tool
#
usage()
{
    echo "usage: maketrack [-p dir] [-b branch] [-e script]"
    echo "    p : pull the source code to directory 'dir'. Default no-pull"
    echo "    b : branch name to pul. default 'master'"
    echo "    e : script to execute. default: 'make' && 'make install'"
    exit 1
}

branch=master

while getopts "pc:e:" opt; do
  case $opt in
    p)
      pull=1
      ;;
    b)
      branch=$OPTARG
      ;;
    e)
      script=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

