#! /bin/bash
#
# Build and deploy - tracker tool
#
usage()
{
    echo "usage: trackit [-p] [-b branch] [-B]
}
while getopts "pc:" opt; do
  case $opt in
    i)
      original=$OPTARG
      ;;
    n)
      nIsos=$OPTARG
      ;;
    m)
      mspecs=($mspecs $OPTARG)
      ;;
    u)
      umod=1
      ;;
    p)
      pDir=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))
